### ISSUE TITLE
Use title case for directories in sidebar

### ISSUE THREAD

**Issue by chrisflatley** [commitd/docs#14]
Nested Directories will typically be lowercase (or likely hyphened lower-cased). Currently this is rendered as is. 

The out of the box experience of sidebar could be improved using formatting with title case (or sentence case).

Can be achieved with https://www.npmjs.com/package/change-case

```
const title = changeCase.titleCase(directoryName)
```

**Comment by stuarthendren** [comment]
I already use startCase from lodash elsewhere - will that do?
https://lodash.com/docs/4.17.15#startCase
