### ISSUE TITLE
Inbuilt search

### ISSUE THREAD

**Issue by chrisflatley** [commitd/docs#21]
Nice to have search index. This would help save our linking everything together, and generally aid the user.

Ideally, this would be offline.

This could start with simple filtering of the side bar (see semantic https://react.semantic-ui.com/)

Then moved to content based search: Docusaurus uses [agolia search](https://docusaurus.io/docs/en/search) which is online.

See Gatsby documentation https://www.gatsbyjs.org/docs/adding-search/

**Comment by jonnyelliot** [comment]
gatsby-plugin-elasticlunr-search Seems to be the most 'out of of the box' approach. And simplest as it is done client side. It builds a search index as part of the yarn build. Trade off is that the client needs to download the index, fine as long as it doesnt get too big.
